import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box, Container, Theme } from "@radix-ui/themes";
import "./globals.css";
import "./theme-config.css";
import NavBar from "./NavBar";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={` ${inter.variable}`}>
                <Theme
                    accentColor="purple"
                    grayColor="gray"
                    panelBackground="solid"
                    scaling="100%"
                    radius="full"
                    className=""
                >
                    <Box className="flex flex-col h-screen">
                        <NavBar />
                        <main className="h-full">{children}</main>
                    </Box>
                </Theme>
            </body>
        </html>
    );
}
